### ISSUE TITLE
A couple of things needed for the vignette

### ISSUE THREAD

**Issue by kbroman** [mdm266/T4rr_project#1]
For the vignette to get built, you need to add a couple of things:

In the YAML header of the `.Rmd` file, include:

```
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Put the title of your vignette here}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8](inputenc)
```

In the `DESCRITION` file, include:

```
Suggests: knitr, rmarkdown
VignetteBuilder: knitr
```

See http://kbroman.org/pkg_primer/pages/vignettes.html

**Comment by mdm266** [comment]
Thanks. Fixed.
