### ISSUE TITLE
Bug in my_Fst

### ISSUE THREAD

**Issue by kbroman** [mdm266/T4rr_project#2]
In your [`my_Fst` function](https://github.com/mdm266/T4rr_project/blob/master/R/my_popgen.R#L38) you have a line like

``` r
avg_p< sum((n*p)/(r*n-bar)) # average allele freq of major allele
```

I think you should change `<` to `<-`, and `n-bar` to `n_bar`.

This shows up in `R CMD check` as "`no visible binding for global variable 'ave_p'`" (and `bar`).

**Comment by mdm266** [comment]
Fixed.
