### ISSUE TITLE
Add documentation for each function

### ISSUE THREAD

**Issue by kbroman** [mdm266/T4rr_project#3]
If you run `R CMD check`, you'll get the warning:

```
Undocumented code objects:
  'my_Fst' 'my_pi' 'my_seg_sites'
```

You need to add help files for each function. I prefer to use Roxygen2 and devtools; see http://kbroman.org/pkg_primer/pages/docs.html

**Comment by mdm266** [comment]
I fixed the documentation, but I get this warning

"checking PDF version of manual... WARNING
Latex errors when creating PDF version"

Is this a formatting issue I accidentally messed with when editing the .RD files? It looks fine to me when I open the PDF.

**Comment by kbroman** [comment]
I'm not getting this problem. There's maybe a latex log file somewhere in the `mypopgen.Rcheck` directory that you can look at. My guess is that your LaTeX setup is missing some packages.
